language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm install -g hexo-cli
  - git submodule update --init --recursive
install:
  - npm install
script:
  - npm run clean
  - npm run build
  - npm run deploy
