language: node_js
node_js: stable
branches:
  only:
    - master
before_install:
  - npm i -g hexo-cli
install:
  - npm i
script:
  - hexo clean
  - hexo generate
after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/xinpuchen/xinpuchen.github.io.git
